name: CI-Debug

on:
  workflow_dispatch:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11] # [ubuntu-18.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/debug/"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/debug/short"

    steps:
    - uses: actions/checkout@v2

    # Check if GitHub Cache has it, because that's free
    - name: Using the builtin GitHub Cache Action for .conan
      if: matrix.os != 'windows-2019'
      id: github-cache-conan
      uses: actions/cache@v1
      env:
        cache-name: cache-conan-modules
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-debug-${{ hashFiles('conanfile.py') }}

    # If GitHub Cache doesn't have it, get from Conan Cache (has git lfs cost)
    - name: Cache Conan modules
      if: steps.github-cache-conan.outputs.cache-hit != 'true'
      id: cache-conan
      uses: turtlebrowser/conan-cache@master
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-center-index-cache
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-debug-${{ hashFiles('conanfile.py') }}
          target_os: ${{ runner.os }}-${{ matrix.os }}-debug
          lfs_limit: 60

      # MacOS 10.15 - XCode version 11.7
      # MacOS 11.1  - XCode version 12.4
      # MacOS 11.3  - XCode version 12.5
      # MacOS 12.0  - XCode version 13.0
    - name: Get right SDK for MacOS 11
      if: startsWith(matrix.os, 'macos-11')
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5'

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Remove all previous builds
      # Mac and not hit in either cache
      if: (matrix.os == 'macos-10.15') && (steps.github-cache-conan.outputs.cache-hit != 'true') && (steps.cache-conan.outputs.cache-hit != 1)
      run: conan remove -f "*"

#    - name: Install patched conan-qt
#      run: |
#        git clone https://github.com/patricia-gallardo/conan-qt.git
#        cd conan-qt
#        git checkout get_opus_from_chromium
#        conan export . qt/5.15.0@patricia-gallardo/patched

    - name: Get Conan Dependencies
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: cmake --build build
