name: CI-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15] # ubuntu-18.04, macos-10.15, windows-2019, ubuntu-20.04

    runs-on: ${{ matrix.os }}
    
    env:
      #CONAN_CPU_COUNT: 6
      CONAN_SYSREQUIRES_MODE: enabled
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      INSTALL_DIR: ${{ github.workspace }}/install/

    steps:
    - uses: actions/checkout@v2

    # Check if GitHub Cache has it, because that's free
    - name: Using the builtin GitHub Cache Action for .conan
      if: matrix.os != 'windows-2019'
      id: github-cache-conan
      uses: actions/cache@v1
      env:
        cache-name: cache-conan-modules
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-${{ hashFiles('conanfile.py') }}

    # If GitHub Cache doesn't have it, get from Conan Cache (has git lfs cost)
    - name: Cache Conan modules
      if: steps.github-cache-conan.outputs.cache-hit != 'true'
      id: cache-conan
      uses: turtlebrowser/conan-cache@master
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-${{ hashFiles('conanfile.py') }}
          target_os: ${{ runner.os }}-${{ matrix.os }}
          lfs_limit: 60

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Make build directory
      run: mkdir build

#    - name: Get Conan
#      run: |
#        pip3 install wheel setuptools
#        pip3 install conan --upgrade
#        mkdir build
        
#    - name: Fix Path on Ubuntu
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' ||  matrix.os == 'ubuntu-16.04'
#      run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

#    - name: Install patched conan-qt
#      run: |
#        git clone https://github.com/patricia-gallardo/conan-qt.git
#        cd conan-qt
#        git checkout get_opus_from_chromium
#        conan export . qt/5.15.0@patricia-gallardo/patched

    - name: Get Conan Dependencies
      working-directory: build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=Release ..

#    - name: Get Licences
#      shell: bash
#      working-directory: ${{ env.CONAN_USER_HOME_SHORT }}
#      env:
#        ABOUT_CREDITS_PATH: "*/qtwebengine/src/core/debug/gen/components/resources/about_credits.html"
#      run: |
#        echo "Try to find the about_credits.html file"
#        find . -wholename  ${{ env.ABOUT_CREDITS_PATH }}
#        find . -wholename  ${{ env.ABOUT_CREDITS_PATH }} -exec cp {} ${{ github.workspace }} \;

    - name: Build
      working-directory: build
      run: cmake --build . --config Release -j 4

    - name: Linux Install
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
      working-directory: build
      run: |
        source ${{ github.workspace }}/build/src/activate_run.sh
        cmake --build . --config Release --target install
        cpack -G "RPM;DEB"
        cp *.deb *.rpm ${{ env.INSTALL_DIR }}

    - name: Windows Install (windeployqt)
      if: matrix.os == 'windows-2019'
      working-directory: build
      run: |
        ${{ github.workspace }}/build/src/activate_run.ps1
        cmake --build . --config Release --target install

    # https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html?highlight=dyld_library_path#using-shared-libraries-from-dependencies
    - name: Mac Install (macdeployqt)
      if: matrix.os == 'macos-10.15'
      working-directory: build
      run: |
        source ${{ github.workspace }}/build/src/activate_run.sh
        DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH DYLD_FRAMEWORK_PATH=$DYLD_FRAMEWORK_PATH cmake --build . --config Release --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact
        path: ${{ env.INSTALL_DIR }}
