name: Update Conan

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 18 * * 1'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0, windows-2019]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      CONAN_SYSREQUIRES_MODE: enabled
      INSTALL_DIR: ${{ github.workspace }}/install/

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conan modules
      id: cache-conan
      uses: turtlebrowser/conan-cache@master
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-update-${{ github.run_number }}
          target_os: ${{ runner.os }}-${{ matrix.os }}
          lfs_limit: 60

    - name: Add 20.04 dependency - Should be builtin in a future conan-qt release
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt install libxcb-dri3-dev

    - name: Add 16.04 dependency - Should be builtin in a future conan-qt release
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get install python3.7
        pip install --upgrade pip
        pip3 install --upgrade pip
        sudo apt-get install libegl1-mesa-dev

    - name: Python2 version
      run: python2 --version

    - name: Python3 version
      run: python3 --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Make build directory
      run: mkdir build

#    - name: Get Conan
#      run: |
#        pip3 install wheel setuptools
#        pip3 install conan --upgrade
#        mkdir build
#        
#    - name: Fix Path on Ubuntu
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'
#      run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

# Debian Dependencies
# https://wiki.qt.io/Building_Qt_5_from_Git

#    - name: Add Qt Source Dependencies
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
#      run: |
#        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
#        sudo apt-get update
#        sudo apt-get build-dep qt5-default

#    - name: Add Libxcb Dependencies
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
#      run: |
#        sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

#    - name: Add Qt WebEngine Dependencies
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
#      run: |
#        sudo apt-get install libssl-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libdbus-1-dev libfontconfig1-dev libcap-dev libxtst-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libxss-dev libegl1-mesa-dev gperf bison

#    - name: Add Qt Multimedia Dependencies - using GStreamer 1.0
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
#      run: |
#        sudo apt-get install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

#    - name: Add QDoc Documentation Generator Tool Dependencies
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
#      run: |
#        sudo apt install libclang-6.0-dev llvm-6.0

#    - name: Remove all previous builds
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-10.15' || matrix.os == 'ubuntu-16.04'
#      run: conan remove -f "*"

    - name: Get Conan Dependencies
      working-directory: build
      run: cmake -DUPDATE_CONAN=ON -DCMAKE_BUILD_TYPE=Release ..
